Resources:
  LambdaTemplate:
      Type: "AWS::Lambda::Function"
      Properties: 
        Code:
          S3Bucket: "mn-lambda-functions"
          S3Key: "cp-lambda-cf-deploy/index.js.zip"
        Description: "Example CodePipeline deploy Lambda with Cloudformation"
        Environment:
          Variables:
            "Region": "us-west-2"
        FunctionName: "CP-Lambda-CF-Deploy"
        Handler: "index.handler"
        MemorySize: 128
        Role: "arn:aws:iam::111648011453:role/lambda_basic_execution"
        Runtime: "nodejs6.10"
        Timeout: 300
        Tags:
          -
            Key: "Department"
            Value: "Development"